### ISSUE TITLE
problemas con los paths 

### ISSUE THREAD

**Issue by mgaitan** [pablocelayes/nacionalesoma#2]
muchachos, estaba intentando desplegar la app en el server, pero hay un problema con todos los paths que están hardcodeados (`../data/...`)

eso puede funcionar para una ejecucion local, donde el directorio relativo es referido al módulo principal que se ejecutó, pero no funciona cuando el modulo se importa porque la app se ejecutó de otra manera (por ejemplo, a través de un servidor wsgi, como en prod). 

Lo correcto siempre es construir los paths con `os.path.join` y referirlos al path del módulo (`os.path.dirname(__file__)`). ejemplo: http://stackoverflow.com/questions/21005822/what-does-os-path-abspathos-path-joinos-path-dirname-file-os-path-pardir

```
2016-02-01 14:15:40 [20487] [INFO] Serving on fd://7
2016-02-01 14:15:40 [20487] [INFO] Using <class 'chaussette.backend._meinheld.Server'> as a backend
Traceback (most recent call last):
  File "/root/.virtualenvs/nombres_cba/bin/chaussette", line 11, in <module>
    sys.exit(main())
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/chaussette/server.py", line 173, in main
    app = import_string(application)
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/chaussette/util.py", line 119, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/root/nacionalesoma/visualizacion/wsgi.py", line 1, in <module>
    from  application import app
Traceback (most recent call last):
  File "/root/.virtualenvs/nombres_cba/bin/chaussette", line 11, in <module>
Traceback (most recent call last):
  File "/root/.virtualenvs/nombres_cba/bin/chaussette", line 11, in <module>
    sys.exit(main())
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/chaussette/server.py", line 173, in main
    sys.exit(main())
  File "/root/nacionalesoma/visualizacion/application.py", line 4, in <module>
    from app import app
  File "/root/nacionalesoma/visualizacion/app/__init__.py", line 5, in <module>
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/chaussette/server.py", line 173, in main
    app = import_string(application)
    app = import_string(application)
    from app import views
  File "/root/nacionalesoma/visualizacion/app/views.py", line 9, in <module>
    from retrieve import data,df_to_response
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/chaussette/util.py", line 119, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/chaussette/util.py", line 119, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/root/nacionalesoma/visualizacion/retrieve.py", line 15, in <module>
    df_tmp = read_csv(file_cat_counts % "aprobados")
  File "/root/nacionalesoma/visualizacion/wsgi.py", line 1, in <module>
    from  application import app
  File "/root/nacionalesoma/visualizacion/wsgi.py", line 1, in <module>
    from  application import app
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 491, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/root/nacionalesoma/visualizacion/application.py", line 4, in <module>
    from app import app
  File "/root/nacionalesoma/visualizacion/application.py", line 4, in <module>
  File "/root/nacionalesoma/visualizacion/app/__init__.py", line 5, in <module>
    from app import views
    from app import app
  File "/root/nacionalesoma/visualizacion/app/__init__.py", line 5, in <module>
    from app import views
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 268, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/nacionalesoma/visualizacion/app/views.py", line 9, in <module>
  File "/root/nacionalesoma/visualizacion/app/views.py", line 9, in <module>
    from retrieve import data,df_to_response
    from retrieve import data,df_to_response
  File "/root/nacionalesoma/visualizacion/retrieve.py", line 15, in <module>
  File "/root/nacionalesoma/visualizacion/retrieve.py", line 15, in <module>
    df_tmp = read_csv(file_cat_counts % "aprobados")
    df_tmp = read_csv(file_cat_counts % "aprobados")
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 583, in __init__
    self._make_engine(self.engine)
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 491, in parser_f
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 491, in parser_f
    return _read(filepath_or_buffer, kwds)
    return _read(filepath_or_buffer, kwds)
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 724, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 268, in _read
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 268, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 583, in __init__
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 583, in __init__
    self._make_engine(self.engine)
    self._make_engine(self.engine)
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 1093, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 724, in _make_engine
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 724, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "pandas/parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3253)
  File "pandas/parser.pyx", line 588, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6112)
    self._engine = CParserWrapper(self.f, **self.options)
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 1093, in __init__
  File "/root/.virtualenvs/nombres_cba/lib/python3.4/site-packages/pandas/io/parsers.py", line 1093, in __init__
    self._reader = _parser.TextReader(src, **kwds)
OSError: File b'../data/aprobados/provcounts.csv' does not exist
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3253)
  File "pandas/parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3253)
  File "pandas/parser.pyx", line 588, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6112)
OSError: File b'../data/aprobados/provcounts.csv' does not exist
  File "pandas/parser.pyx", line 588, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6112)
OSError: File b'../data/aprobados/provcounts.csv' does not exist
^C2016-02-01 09:15:45 circus[20478] [INFO] Got signal SIG_INT
```

**Comment by pablocelayes** [comment]
Gracias Tin por la mano con esto, y perdón por la demora en contestar, he estado viajando hasta hace una semana, y en 10 días me estoy mudando a Holanda.

Parte del objetivo de la tarea es que @alejandrozf  aprenda a hacer el deploy por sí mismo.

Yo en su momento lo había referido al post[1] de tu blog sobre Circus, Chausette y Django. No sé si te parece suficiente eso o qué recomendarías que vea para poderlo hacer él mismo.

[1] http://mgaitan.github.io/posts/deploy-de-django-con-circus-chaussette-nginx.html

**Comment by alejandrozf** [comment]
Bueno ya puse a correr la app en el server, trabajé en lo de las rutas, les pido valoren si se puede cerrar el issue.

Saludos!

**Comment by pablocelayes** [comment]
¡Buenísimo @alejandrozf ! Ahora tendríamos que ponerle una URL piola, puede ser algo como:

http://lab.opendatacordoba.org/nacionalesoma

@mgaitan , ¿tu app de los nombres de los padrones en qué URL estaba? ¿Me confirmás que sigue funcionando?
